project:
  type: website

website:
  title: "Shiva"
  navbar:  
    background: primary
    pinned: true
    left:
      - href: index.qmd
        icon: house-fill
        text: Home
      - text: Portfolio
        icon: trophy
        href: portfolio/index.qmd
      - text: Blog
        icon: substack
        href: blog/index.qmd
    
    right:
      - text: About    
        href: about.qmd
        icon: file-person-fill            
      - icon: github
        href: https://github.com/mshiva
      - icon: linkedin
        href: https://linkedin.com/in/sivabalanmuthukumar

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



