project:
  type: website

website:
  title: "Shiva"
  navbar:  
    background: primary
    pinned: true
    left:
      - href: index.qmd
        text: Home
    
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mshiva
      - icon: linkedin
        href: https://linkedin.com/sivabalanmuthukumar

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



